"""add_ai_analysis_column

Revision ID: fd9d26032371
Revises: 514065a9d556
Create Date: 2025-11-28 11:32:54.337836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9d26032371'
down_revision: Union[str, None] = '514065a9d556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('ai_analysis_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'ai_analysis_json')
    # ### end Alembic commands ###
